-- SQL Script to seed products for PT. Prima Integrasi Network
-- This script clears the existing products table and inserts the 5 specified products:
-- 1. Data
-- 2. Infrastructure
-- 3. Cybersecurity
-- 4. Network & Connectivity
-- 5. Collaboration & Smart School, Campus, Office
--
-- You can run this in your Linux VPS bash:
-- mysql -u your_username -p your_database_name < seed_products.sql

-- 1. Clear existing products
DELETE FROM `products`;

-- 2. Insert the 5 products
INSERT INTO `products` (
  `id`,
  `name`,
  `slug`,
  `category`,
  `short_description`,
  `description`,
  `features`,
  `benefits`,
  `specifications`,
  `target_segment`,
  `image_url`,
  `gallery`,
  `brochure_url`,
  `video_url`,
  `price_range`,
  `order_number`,
  `is_featured`,
  `is_active`,
  `meta_title`,
  `meta_description`,
  `created_at`,
  `updated_at`
) VALUES
(
  1,
  'Data',
  'data',
  'Data & Analytics',
  'Enterprise data solutions including database management, governance, warehousing, integration, and AI-ready architectures.',
  'Our Data Solutions help enterprises securely store, organize, govern, and analyze their mission-critical information. We specialize in high-performance Oracle Database administration, secure database consolidation, real-time data replication, data warehousing, and modern analytics platforms. We enable organizations to maintain 24/7 availability and turn raw operational data into actionable, compliance-ready business intelligence.',
  '["Oracle Database Administration & Tuning", "Real-Time Data Integration & ETL", "Enterprise Data Warehousing & Big Data", "Data Governance, Security & Auditing"]',
  '["Ensures 99.999% database uptime and reliability", "Reduces database licensing and hardware footprints", "Unlocks fast, analytics-driven decision-making", "Ensures compliance with national data privacy regulations"]',
  '{"Database Supported":["Oracle 19c/23c","MySQL Enterprise","PostgreSQL"],"Data Integration":["Oracle GoldenGate","Microsoft SSIS"],"Platform Readiness":["Cloud-native","On-Premise","Hybrid Hybrid-Cloud"]}',
  'Financial Institutions, Government Agencies, Telcos, Large Enterprises',
  NULL,
  '[]',
  NULL,
  NULL,
  'Enterprise Grade',
  1,
  1,
  1,
  'Enterprise Data & Database Solutions | PINET',
  'Maximize database performance, governance, and analytics with PINET enterprise data solutions. Certified Oracle database services.',
  NOW(),
  NOW()
),
(
  2,
  'Infrastructure',
  'infrastructure',
  'IT Infrastructure',
  'High-performance computing, virtualization, hyperconverged infrastructure, storage, and hybrid cloud orchestration.',
  'We design, deploy, and manage robust, resilient IT infrastructure optimized for mission-critical enterprise workloads. Leveraging partnership architectures like Oracle Engineered Systems (Exadata, ODA), hyperconverged infrastructure (HCI), enterprise storage arrays, and secure virtualization, we build the foundation of your digital transformation. Our solutions guarantee sub-second transaction performance, robust data protection, and seamless migration pathways to public, private, or hybrid clouds.',
  '["Oracle Engineered Systems (Exadata, ODA)", "Hyperconverged Infrastructure (HCI)", "Enterprise SAN & NAS Storage Arrays", "Hybrid Cloud Integration & Orchestration"]',
  '["Sub-second database performance and response times", "Simplified infrastructure operations and lower overhead", "Highly scalable compute and storage capacity", "Fast, non-disruptive cloud migration pathways"]',
  '{"Engineered Systems":["Oracle Exadata","Oracle Database Appliance"],"HCI Solutions":["VMware vSAN","Nutanix"],"Storage Platforms":["Oracle ZFS","Dell EMC","HPE"]}',
  'Banks, Government, Healthcare, Enterprise Data Centers',
  NULL,
  '[]',
  NULL,
  NULL,
  'Enterprise Grade',
  2,
  1,
  1,
  'Mission-Critical IT Infrastructure Solutions | PINET',
  'Build a reliable, scalable foundation with PINET IT Infrastructure solutions, featuring Oracle Exadata, ODA, HCI, and hybrid cloud.',
  NOW(),
  NOW()
),
(
  3,
  'Cybersecurity',
  'cybersecurity',
  'Security & Compliance',
  'Comprehensive security architectures covering network defenses, identity access management, endpoints, threat hunting, and compliance.',
  'Protect your digital enterprise assets and user identities with our comprehensive security systems. PINET delivers end-to-end security architectures covering Next-Generation Firewalls, Identity & Access Management (IAM), Endpoint Detection & Response (EDR), and Cloud Security controls. We help you establish proactive security policies, secure remote working environments, and implement Security Operations Center (SOC) practices to identify, block, and mitigate emerging cyber threats in real-time.',
  '["Next-Generation Firewalls & Intrusion Prevention", "Identity & Access Management (IAM / MFA)", "Endpoint Detection & Incident Response (EDR)", "Security Information & Event Management (SIEM)"]',
  '["Prevents data breaches and malware incidents", "Secures remote access for hybrid workforces", "Achieves strict industry compliance standards", "Provides real-time visibility and threat monitoring"]',
  '{"Firewall Partners":["Fortinet","Palo Alto","Cisco"],"IAM Technologies":["MFA","Single Sign-On (SSO)","Privileged Access"],"EDR Solutions":["CrowdStrike","SentinelOne"]}',
  'E-Commerce, Banking, Logistics, Multi-Branch Corporates',
  NULL,
  '[]',
  NULL,
  NULL,
  'Enterprise Grade',
  3,
  1,
  1,
  'Enterprise Cybersecurity & Threat Mitigation | PINET',
  'Safeguard your corporate network, endpoints, and user access with PINET end-to-end cybersecurity systems and compliance services.',
  NOW(),
  NOW()
),
(
  4,
  'Network & Connectivity',
  'network-connectivity',
  'Networking & SD-WAN',
  'Enterprise-grade networking, Software-Defined WAN (SD-WAN), campus wireless, core routing, and switching infrastructure.',
  'Achieve seamless, high-speed, and secure connectivity across your branches, head office, data centers, and cloud applications. We provide comprehensive network design, high-performance routing and switching, Software-Defined WAN (SD-WAN) integration, secure campus-wide wireless networks, and intelligent network management. Our connectivity architectures ensure maximum bandwidth efficiency, automatic link failover, and end-to-end payload encryption.',
  '["Software-Defined WAN (SD-WAN) Deployments", "Core Routing & High-Capacity Switching", "Secure Enterprise Wireless Networks", "Real-Time Network Performance Monitoring"]',
  '["Improves application speed and connection stability", "Reduces WAN operational costs up to 50%", "Ensures zero-downtime with automatic failovers", "Simplifies multi-branch network management"]',
  '{"SD-WAN Partners":["Fortinet SD-WAN","Cisco SD-WAN"],"Routing & Switching":["Cisco Catalyst","HPE Aruba"],"Wireless APs":["Aruba AP","Ruckus"]}',
  'Retail Chains, Manufacturing, Education, Branch-Heavy Businesses',
  NULL,
  '[]',
  NULL,
  NULL,
  'Enterprise Grade',
  4,
  1,
  1,
  'Enterprise Networking & SD-WAN Solutions | PINET',
  'Optimize branch connectivity, speed up applications, and reduce costs with PINET SD-WAN, core networking, and wireless solutions.',
  NOW(),
  NOW()
),
(
  5,
  'Collaboration & Smart School, Campus, Office',
  'collaboration-smart-school-campus-office',
  'Smart Solutions & Collaboration',
  'Integrated smart spaces, digital classrooms, hybrid collaboration systems, smart office automation, and unified communications.',
  'Transform traditional workspaces and educational institutions into modern, intelligent, and highly collaborative spaces. Our Smart Solutions integrate interactive digital displays, smart hybrid classroom technology, automated school/campus attendance systems, unified IP telephony, smart video conferencing rooms, and building automation sensors. We empower teams and students to collaborate effortlessly in physical, remote, or hybrid setups while optimizing facility usage.',
  '["Smart Classroom & Interactive Whiteboards", "Hybrid Meeting Rooms & AV Systems", "Unified IP Telephony & Video Conferencing", "Smart Space Automation & Access Control"]',
  '["Fosters active engagement in classrooms and offices", "Enables seamless remote and hybrid collaborations", "Reduces energy costs via automated space utility controls", "Streamlines communication channels into a single app"]',
  '{"Interactive Displays":["Maxhub","Clevertouch"],"Meeting AV":["Poly","Logitech","Yealink"],"IP PBX & Telephony":["Yeastar","Cisco CallManager"]}',
  'Schools, Universities, Government Offices, Modern Workspaces',
  NULL,
  '[]',
  NULL,
  NULL,
  'Enterprise Grade',
  5,
  1,
  1,
  'Smart Solutions for School, Campus & Office | PINET',
  'Transform spaces with PINET smart systems, interactive digital classrooms, hybrid meeting rooms, and unified communications.',
  NOW(),
  NOW()
);
