-- SQL Script to seed Events for PT. Prima Integrasi Network
-- You can run this in your terminal:
-- mysql -u root -prich0505 company_profile < seed_events.sql

-- 1. Create table events if not exists
CREATE TABLE IF NOT EXISTS `events` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(300) NOT NULL UNIQUE,
  `description` LONGTEXT NULL,
  `event_type` ENUM('seminar', 'workshop', 'conference', 'webinar', 'training', 'exhibition', 'other') NOT NULL DEFAULT 'seminar',
  `start_date` DATE NOT NULL,
  `end_date` DATE NULL,
  `start_time` TIME NULL,
  `end_time` TIME NULL,
  `location` VARCHAR(255) NULL,
  `venue` VARCHAR(255) NULL,
  `address` TEXT NULL,
  `is_online` TINYINT(1) NOT NULL DEFAULT 0,
  `meeting_link` VARCHAR(255) NULL,
  `featured_image` VARCHAR(255) NULL,
  `gallery` TEXT NULL COMMENT 'JSON array of image URLs',
  `organizer` VARCHAR(100) NULL,
  `contact_person` VARCHAR(100) NULL,
  `contact_email` VARCHAR(100) NULL,
  `contact_phone` VARCHAR(50) NULL,
  `registration_url` VARCHAR(255) NULL,
  `max_participants` INT NULL,
  `is_featured` TINYINT(1) NOT NULL DEFAULT 0,
  `is_published` TINYINT(1) NOT NULL DEFAULT 0,
  `status` ENUM('upcoming', 'ongoing', 'completed', 'cancelled') NOT NULL DEFAULT 'upcoming',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 2. Clear existing events
DELETE FROM `events`;

-- 3. Insert events data
INSERT INTO `events` (
  `title`,
  `slug`,
  `description`,
  `event_type`,
  `start_date`,
  `end_date`,
  `start_time`,
  `end_time`,
  `location`,
  `venue`,
  `address`,
  `is_online`,
  `meeting_link`,
  `featured_image`,
  `gallery`,
  `organizer`,
  `contact_person`,
  `contact_email`,
  `contact_phone`,
  `registration_url`,
  `max_participants`,
  `is_featured`,
  `is_published`,
  `status`,
  `created_at`,
  `updated_at`
) VALUES
(
  'Oracle Cloud Infrastructure (OCI) Modernization Workshop 2026',
  'oracle-cloud-infrastructure-oci-modernization-workshop-2026',
  'Learn how to optimize database workloads and deploy hybrid cloud configurations on Oracle Cloud Infrastructure (OCI). This hands-on workshop led by PINET senior engineers is designed for IT admins, database administrators, and cloud architects.',
  'workshop',
  '2026-07-15',
  '2026-07-15',
  '09:00:00',
  '15:00:00',
  'Jakarta',
  'PINET Enterprise Training Center',
  'Gedung PINET Lt. 4, Jl. Jend. Sudirman No. 21, Jakarta Selatan',
  0,
  NULL,
  '/assets/images/events/oci-workshop-2026.jpg',
  '["/assets/images/events/oci-workshop-gallery1.jpg"]',
  'PT. Prima Integrasi Network',
  'Ayu Rejeki',
  'ayurejeki249@gmail.com',
  '+6281234567890',
  'https://pinet.co.id/events/oci-workshop-2026/register',
  30,
  1,
  1,
  'upcoming',
  NOW(),
  NOW()
),
(
  'Indonesia Enterprise AI Summit 2026',
  'indonesia-enterprise-ai-summit-2026',
  'Discover how modern enterprises and government agencies in Indonesia are leveraging artificial intelligence. Co-hosted by PINET, Oracle, and IBM, this summit features keynote speakers, case studies on GovTech, and panel discussions on AI-driven cybersecurity.',
  'conference',
  '2026-08-20',
  '2026-08-20',
  '08:30:00',
  '17:00:00',
  'Jakarta',
  'Grand Ballroom, Hotel Indonesia Kempinski',
  'Jl. MH Thamrin No. 1, Menteng, Jakarta Pusat',
  0,
  NULL,
  '/assets/images/events/ai-summit-2026.jpg',
  '["/assets/images/events/ai-summit-gallery1.jpg"]',
  'PT. Prima Integrasi Network & Oracle Indonesia',
  'Ayu Rejeki',
  'ayurejeki249@gmail.com',
  '+6281234567890',
  'https://pinet.co.id/events/ai-summit-2026/register',
  200,
  1,
  1,
  'upcoming',
  NOW(),
  NOW()
),
(
  'Masterclass: Securing Enterprise Hybrid Cloud with AI-Driven Threat Hunting',
  'masterclass-securing-hybrid-cloud-ai-threat-hunting',
  'In an era of rising cybersecurity challenges, traditional network perimeters are no longer enough. Join our technical webinar with cybersecurity experts from Cisco and Trend Micro as they demo AI-driven security detection and autonomous threat response.',
  'webinar',
  '2026-09-10',
  '2026-09-10',
  '14:00:00',
  '16:00:00',
  'Online',
  'Zoom Webinar',
  NULL,
  1,
  'https://zoom.us/j/9876543210',
  '/assets/images/events/cybersecurity-webinar-2026.jpg',
  NULL,
  'PT. Prima Integrasi Network',
  'Ayu Rejeki',
  'ayurejeki249@gmail.com',
  '+6281234567890',
  'https://pinet.co.id/events/cybersecurity-webinar-2026/register',
  500,
  0,
  1,
  'upcoming',
  NOW(),
  NOW()
);
