-- SQL Script to seed Careers for PT. Prima Integrasi Network
-- You can run this in your terminal:
-- mysql -u root -prich0505 company_profile < seed_careers.sql

-- 1. Create table careers if not exists
CREATE TABLE IF NOT EXISTS `careers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `job_title` VARCHAR(200) NOT NULL,
  `slug` VARCHAR(255) NOT NULL UNIQUE,
  `department` VARCHAR(100) NULL COMMENT 'e.g., IT, Sales, Marketing, HR',
  `location` VARCHAR(100) NULL,
  `employment_type` ENUM('full_time', 'part_time', 'contract', 'internship', 'freelance') NOT NULL DEFAULT 'full_time',
  `experience_level` ENUM('entry', 'junior', 'mid', 'senior', 'lead', 'manager') NULL,
  `salary_range` VARCHAR(100) NULL,
  `description` LONGTEXT NOT NULL,
  `responsibilities` LONGTEXT NULL COMMENT 'JSON array of responsibilities',
  `requirements` LONGTEXT NULL COMMENT 'JSON array of requirements',
  `qualifications` TEXT NULL COMMENT 'JSON array of qualifications',
  `benefits` TEXT NULL COMMENT 'JSON array of benefits',
  `application_deadline` DATETIME NULL,
  `posted_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `contact_email` VARCHAR(100) NULL,
  `application_url` VARCHAR(255) NULL,
  `views` INT NOT NULL DEFAULT 0,
  `is_featured` TINYINT(1) NOT NULL DEFAULT 0,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `status` ENUM('open', 'closed', 'on_hold') NOT NULL DEFAULT 'open',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 2. Clear existing careers
DELETE FROM `careers`;

-- 3. Insert careers data
INSERT INTO `careers` (
  `job_title`,
  `slug`,
  `department`,
  `location`,
  `employment_type`,
  `experience_level`,
  `salary_range`,
  `description`,
  `responsibilities`,
  `requirements`,
  `qualifications`,
  `benefits`,
  `application_deadline`,
  `posted_date`,
  `contact_email`,
  `application_url`,
  `views`,
  `is_featured`,
  `is_active`,
  `status`,
  `created_at`,
  `updated_at`
) VALUES
(
  'Senior Oracle Database Administrator (DBA)',
  'senior-oracle-database-administrator-dba',
  'Infrastructure',
  'Jakarta (Hybrid)',
  'full_time',
  'senior',
  'Rp 18.000.000 - Rp 25.000.000',
  'PT. Prima Integrasi Network is seeking an experienced Senior Oracle DBA to oversee, design, and optimize our enterprise customers\' database infrastructure. You will work on-site and remotely with high-availability systems including Oracle Exadata, RAC, and OCI.',
  '["Manage, configure, and maintain multi-tenant Oracle database environments", "Implement high availability database architectures using Oracle Real Application Clusters (RAC) and Data Guard", "Diagnose, troubleshoot, and resolve complex database performance issues", "Perform backup and recovery operations using Oracle Recovery Manager (RMAN)", "Collaborate with cloud engineers to manage databases on OCI"]',
  '["5+ years of active experience as an Oracle Database Administrator", "Strong knowledge of Oracle database architecture, ASM, RAC, and GoldenGate", "Proven experience with performance tuning, query optimization, and capacity planning", "Experience with cloud platforms (specifically OCI) is highly desired", "Strong English communication skills"]',
  '["Bachelor\'s degree in Computer Science, Information Technology, or related disciplines", "Oracle Database Administration Certified Professional (OCP) certification is highly preferred"]',
  '["Competitive salary and performance bonuses", "Comprehensive family health insurance", "Professional development and database certifications sponsored by PINET", "Flexible hybrid working arrangement"]',
  '2026-08-31 23:59:59',
  '2026-06-15 12:00:00',
  'careers@pinet.co.id',
  'https://pinet.co.id/careers/apply/senior-oracle-dba',
  12,
  1,
  1,
  'open',
  NOW(),
  NOW()
),
(
  'Cloud Infrastructure Engineer (OCI & Hybrid Cloud)',
  'cloud-infrastructure-engineer-oci-hybrid-cloud',
  'Cloud Operations',
  'Jakarta',
  'full_time',
  'mid',
  'Rp 12.000.000 - Rp 17.000.000',
  'We are looking for a Cloud Infrastructure Engineer to design, deploy, and manage public and hybrid cloud solutions. In this role, you will be instrumental in migrating on-premise infrastructure to Oracle Cloud Infrastructure (OCI) and VMware for enterprise clients.',
  '["Provision, configure, and manage cloud infrastructure elements on OCI", "Migrate on-premise servers, storage, and networking to OCI", "Develop infrastructure as code scripts using Terraform", "Monitor cloud environments and optimize costs and resources", "Provide third-level support for cloud-related incidents"]',
  '["3+ years of experience in system engineering, virtualization, or cloud administration", "Hands-on experience configuring OCI, AWS, or Azure services", "Familiarity with Infrastructure as Code (IaC) tools like Terraform", "Understanding of network topology, DNS, and secure VPN setup", "Ability to work collaboratively in a team environment"]',
  '["Bachelor\'s degree in Computer Engineering, Network Engineering, or related fields", "OCI Cloud Architect Associate certification is a strong plus"]',
  '["Competitive base salary", "Health and dental coverage", "Sponsorship for OCI, VMware, or Red Hat certifications", "Career advancement paths in cloud architecture"]',
  '2026-09-15 23:59:59',
  '2026-06-15 12:00:00',
  'careers@pinet.co.id',
  'https://pinet.co.id/careers/apply/cloud-infrastructure-engineer',
  8,
  0,
  1,
  'open',
  NOW(),
  NOW()
),
(
  'Enterprise AI Solutions Engineer',
  'enterprise-ai-solutions-engineer',
  'Data & AI',
  'Jakarta (Hybrid)',
  'full_time',
  'mid',
  'Rp 14.000.000 - Rp 20.000.000',
  'Join our newly formed Data & AI practice. As an Enterprise AI Solutions Engineer, you will build, integrate, and deploy advanced AI solutions, including Retrieval-Augmented Generation (RAG) and LLM-based agents using platforms like IBM watsonx for our clients.',
  '["Develop and integrate AI agents and LLMs into client software platforms", "Design and maintain vectorized databases and RAG pipelines", "Collaborate with data engineers to ingest, clean, and structure text datasets", "Conduct testing and benchmarking of model latency and accuracy", "Build custom client prototypes and demos"]',
  '["2+ years of professional development experience using Python", "Hands-on experience with LLM frameworks (LangChain, LlamaIndex, or AutoGen)", "Experience with vector databases such as Milvus, Pinecone, or pgvector", "Familiarity with containerized applications (Docker) and RESTful APIs", "Strong analytical skills and passion for artificial intelligence"]',
  '["Bachelor\'s degree in Data Science, Computer Science, Statistics, or equivalent analytical field", "Demonstrated GitHub portfolio of AI or machine learning projects"]',
  '["Competitive salary and flexible working hours", "Opportunities to work on cutting-edge AI and agentic software", "Health and wellness allowance", "Ongoing learning resources and conference attendance support"]',
  '2026-08-15 23:59:59',
  '2026-06-15 12:00:00',
  'careers@pinet.co.id',
  'https://pinet.co.id/careers/apply/enterprise-ai-solutions-engineer',
  15,
  1,
  1,
  'open',
  NOW(),
  NOW()
);
